name = input("What is your name?") 
print("shut up",name)
age= input("How old are you?")
print(age,"Damn you old my boy")
color= input("What is your favorite color?")
print(color,"sucks")
print("So your name is",name,"You are",age,"years old and your favorite color is",color,"damn I feel bad for you.")