name = input("What is your name?") 
print("Hi",name)
age= input("How old are you?")
print(age,"Nice")
color= input("What is your favorite color?")
print(color,"is cool")
print("So your name is",name,"you are",age,"years old and your favorite color is",color,",wow that is so cool.")
print('Hasta lavista')