name = input("What is your name?") 
print("pipe down",name)
age= input("How old are you?")
print(age,"Damn you old my boy")
color= input("What is your favorite color?")
print(color,"sucks")
print("So your name is",name,"you are",age,"years old and your favorite color is",color,",damn I feel bad for you.")
print('kick rocks kid')